const { contextBridge, ipcRenderer, shell, webFrame } = require('electron');

// Note: preload runs sandboxed (Electron default with contextIsolation +
// nodeIntegration:false). Only the `electron` module is requireable —
// Node built-ins like `path`, `fs`, `http` are NOT available here. Anything
// that needs those has to live in main and reach the renderer via IPC.

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  openExternal: (url) => ipcRenderer.send('open-external', url),
  copyToClipboard: (text) => ipcRenderer.invoke('copy-to-clipboard', text),
  onSpots: (cb) => ipcRenderer.on('spots', (_e, data) => cb(data)),
  onSpotsError: (cb) => ipcRenderer.on('spots-error', (_e, msg) => cb(msg)),
  onCatStatus: (cb) => ipcRenderer.on('cat-status', (_e, s) => cb(s)),
  tune: (frequency, mode, bearing, slicePort) => ipcRenderer.send('tune', { frequency, mode, bearing, slicePort }),
  onTuneBlocked: (cb) => ipcRenderer.on('tune-blocked', (_e, msg) => cb(msg)),
  onSmartSdrUnreachable: (cb) => ipcRenderer.on('smartsdr-unreachable', (_e, data) => cb(data)),
  onExternalAtuStart: (cb) => ipcRenderer.on('external-atu-start', (_e, d) => cb(d)),
  onExternalAtuComplete: (cb) => ipcRenderer.on('external-atu-complete', () => cb()),
  externalAtuCancel: () => ipcRenderer.send('external-atu-cancel'),
  rotateTo: (azimuth) => ipcRenderer.send('rotate-to', azimuth),
  refresh: () => ipcRenderer.send('refresh'),
  getSdrDirectory: () => ipcRenderer.invoke('get-sdr-directory'),
  // ECHOCAT mobile-app pairing
  echocatCreatePairingQr: (opts) => ipcRenderer.invoke('echocat-create-pairing-qr', opts || {}),
  echocatListPairedDevices: () => ipcRenderer.invoke('echocat-list-paired-devices'),
  echocatRevokeDevice: (deviceId) => ipcRenderer.invoke('echocat-revoke-device', deviceId),
  echocatTailscaleStatus: () => ipcRenderer.invoke('echocat-tailscale-status'),
  echocatIssueTailscaleCert: () => ipcRenderer.invoke('echocat-issue-tailscale-cert'),
  echocatPickFile: (opts) => ipcRenderer.invoke('echocat-pick-file', opts || {}),
  echocatRestartAudio: () => ipcRenderer.invoke('echocat-restart-audio'),
  onEchocatPairedDevices: (cb) => ipcRenderer.on('echocat-paired-devices', (_e, list) => cb(list)),
  pairPopoutOpen: () => ipcRenderer.send('pair-popout-open'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getRigModels: () => ipcRenderer.invoke('get-rig-models'),
  saveSettings: (s) => ipcRenderer.invoke('save-settings', s),
  listPorts: () => ipcRenderer.invoke('list-ports'),
  listRigs: () => ipcRenderer.invoke('list-rigs'),
  testHamlib: (config) => ipcRenderer.invoke('test-hamlib', config),
  testSerialCat: (config) => ipcRenderer.invoke('test-serial-cat', config),
  testIcomCiv: (config) => ipcRenderer.invoke('test-icom-civ', config),
  connectCat: (target) => ipcRenderer.send('connect-cat', target),
  onCatFrequency: (cb) => ipcRenderer.on('cat-frequency', (_e, hz) => cb(hz)),
  onCatMode: (cb) => ipcRenderer.on('cat-mode', (_e, mode) => cb(mode)),
  onCatPower: (cb) => ipcRenderer.on('cat-power', (_e, watts) => cb(watts)),
  onCatSmeter: (cb) => ipcRenderer.on('cat-smeter', (_e, val) => cb(val)),
  onCatSwr: (cb) => ipcRenderer.on('cat-swr', (_e, val) => cb(val)),
  onCatSwrRatio: (cb) => ipcRenderer.on('cat-swr-ratio', (_e, val) => cb(val)),
  onCatAlc: (cb) => ipcRenderer.on('cat-alc', (_e, val) => cb(val)),
  qrzLookup: (callsign) => ipcRenderer.invoke('qrz-lookup', callsign),
  qrzCheckSub: (force) => ipcRenderer.invoke('qrz-check-sub', force),
  qrzVerifyApiKey: (key) => ipcRenderer.invoke('qrz-verify-api-key', key),
  getReleaseNotes: (version) => ipcRenderer.invoke('get-release-notes', version),
  importAdif: () => ipcRenderer.invoke('import-adif'),
  parseAdif: () => ipcRenderer.invoke('parse-adif'),
  onDxccData: (cb) => ipcRenderer.on('dxcc-data', (_e, data) => cb(data)),
  onClusterStatus: (cb) => ipcRenderer.on('cluster-status', (_e, s) => cb(s)),
  onCwSpotsStatus: (cb) => ipcRenderer.on('cw-spots-status', (_e, s) => cb(s)),
  onRbnSpots: (cb) => ipcRenderer.on('rbn-spots', (_e, data) => cb(data)),
  onRbnStatus: (cb) => ipcRenderer.on('rbn-status', (_e, s) => cb(s)),
  onPskrStatus: (cb) => ipcRenderer.on('pskr-status', (_e, s) => cb(s)),
  onPskrMapSpots: (cb) => ipcRenderer.on('pskr-map-spots', (_e, data) => cb(data)),
  onPskrMapStatus: (cb) => ipcRenderer.on('pskr-map-status', (_e, s) => cb(s)),
  clearPskrMap: () => ipcRenderer.send('pskr-map-clear'),
  onAgStatus: (cb) => ipcRenderer.on('ag-status', (_e, s) => cb(s)),
  onAgAntennaNames: (cb) => ipcRenderer.on('ag-antenna-names', (_e, names) => cb(names)),
  onAgPortStatus: (cb) => ipcRenderer.on('ag-port-status', (_e, s) => cb(s)),
  clearRbn: () => ipcRenderer.send('rbn-clear'),
  onSolarData: (cb) => ipcRenderer.on('solar-data', (_e, d) => cb(d)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, d) => cb(d)),
  onUpdaterActive: (cb) => ipcRenderer.on('updater-active', (_e, active) => cb(active)),
  onDownloadProgress: (cb) => ipcRenderer.on('update-download-progress', (_e, d) => cb(d)),
  onUpdateError: (cb) => ipcRenderer.on('update-error', (_e, msg) => cb(msg)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', () => cb()),
  onUpdateUpToDate: (cb) => ipcRenderer.on('update-up-to-date', () => cb()),
  startDownload: () => ipcRenderer.send('start-download'),
  installUpdate: () => ipcRenderer.send('install-update'),
  checkForUpdates: () => ipcRenderer.send('check-for-updates'),
  onCatLog: (cb) => ipcRenderer.on('cat-log', (_e, msg) => cb(msg)),
  onWorkedQsos: (cb) => ipcRenderer.on('worked-qsos', (_e, data) => cb(data)),
  onWorkedParks: (cb) => ipcRenderer.on('worked-parks', (_e, data) => cb(data)),
  onCreditedParks: (cb) => ipcRenderer.on('credited-parks', (_e, refs) => cb(refs)),
  choosePotaParksFile: () => ipcRenderer.invoke('choose-pota-parks-file'),
  onWsjtxStatus: (cb) => ipcRenderer.on('wsjtx-status', (_e, s) => cb(s)),
  onWsjtxState: (cb) => ipcRenderer.on('wsjtx-state', (_e, s) => cb(s)),
  onWsjtxDecode: (cb) => ipcRenderer.on('wsjtx-decode', (_e, d) => cb(d)),
  onWsjtxClear: (cb) => ipcRenderer.on('wsjtx-clear', () => cb()),
  onWsjtxQsoLogged: (cb) => ipcRenderer.on('wsjtx-qso-logged', (_e, q) => cb(q)),
  onWsjtxActivatorQso: (cb) => ipcRenderer.on('wsjtx-activator-qso', (_e, c) => cb(c)),
  wsjtxReply: (decode) => ipcRenderer.send('wsjtx-reply', decode),
  wsjtxHaltTx: () => ipcRenderer.send('wsjtx-halt-tx'),
  saveQso: (qsoData) => ipcRenderer.invoke('save-qso', qsoData),
  quickRespot: (data) => ipcRenderer.invoke('quick-respot', data),
  sendClusterCommand: (text, nodeId) => ipcRenderer.invoke('send-cluster-command', text, nodeId),
  getRecentQsos: () => ipcRenderer.invoke('get-recent-qsos'),
  getAllQsos: () => ipcRenderer.invoke('get-all-qsos'),
  updateQso: (data) => ipcRenderer.invoke('update-qso', data),
  deleteQso: (idx) => ipcRenderer.invoke('delete-qso', idx),
  deleteQsosByMatch: (match) => ipcRenderer.invoke('delete-qsos-by-match', match),
  updateQsosByMatch: (data) => ipcRenderer.invoke('update-qsos-by-match', data),
  getDefaultLogPath: () => ipcRenderer.invoke('get-default-log-path'),
  chooseLogFile: (currentPath) => ipcRenderer.invoke('choose-log-file', currentPath),
  exportAdif: (qsos) => ipcRenderer.invoke('export-adif', qsos),
  onQrzData: (cb) => ipcRenderer.on('qrz-data', (_e, data) => cb(data)),
  onDonorCallsigns: (cb) => ipcRenderer.on('donor-callsigns', (_e, data) => cb(data)),
  onExpeditionCallsigns: (cb) => ipcRenderer.on('expedition-callsigns', (_e, data) => cb(data)),
  // Directory (HF Nets & SWL Broadcasts)
  onDirectoryData: (cb) => ipcRenderer.on('directory-data', (_e, data) => cb(data)),
  fetchDirectory: () => ipcRenderer.send('fetch-directory'),
  getDirectory: () => ipcRenderer.invoke('get-directory'),
  // Events system
  onActiveEvents: (cb) => ipcRenderer.on('active-events', (_e, data) => cb(data)),
  getActiveEvents: () => ipcRenderer.invoke('get-active-events'),
  setEventOptIn: (data) => ipcRenderer.invoke('set-event-optin', data),
  getEventProgress: (eventId) => ipcRenderer.invoke('get-event-progress', eventId),
  markEventRegion: (data) => ipcRenderer.invoke('mark-event-region', data),
  resetEventProgress: (eventId) => ipcRenderer.invoke('reset-event-progress', eventId),
  exportEventAdif: (data) => ipcRenderer.invoke('export-event-adif', data),
  minimize: () => ipcRenderer.send('win-minimize'),
  maximize: () => ipcRenderer.send('win-maximize'),
  close: () => ipcRenderer.send('win-close'),
  // Pop-out map
  popoutMapOpen: () => ipcRenderer.send('popout-map-open'),
  // Pop-out propagation map
  propPopoutOpen: () => ipcRenderer.send('prop-popout-open'),
  onPropPopoutStatus: (cb) => ipcRenderer.on('prop-popout-status', (_e, open) => cb(open)),
  popoutMapClose: () => ipcRenderer.send('popout-map-close'),
  sendPopoutSpots: (data) => ipcRenderer.send('popout-map-spots', data),
  sendPopoutTuneArc: (data) => ipcRenderer.send('popout-map-tune-arc', data),
  sendPopoutHome: (data) => ipcRenderer.send('popout-map-home', data),
  sendPopoutTheme: (theme) => ipcRenderer.send('popout-map-theme', theme),
  sendColorblindMode: (enabled) => ipcRenderer.send('colorblind-mode', enabled),
  sendWcagMode: (enabled) => ipcRenderer.send('wcag-mode', enabled),
  onPopoutMapStatus: (cb) => ipcRenderer.on('popout-map-status', (_e, open) => cb(open)),
  onPopoutOpenLog: (cb) => ipcRenderer.on('popout-open-log', (_e, spot) => cb(spot)),
  // Pop-out QSO log
  qsoPopoutOpen: () => ipcRenderer.send('qso-popout-open'),
  openLogPopout: (prefill) => ipcRenderer.send('log-popout-open', prefill),
  logPopoutTheme: (theme) => ipcRenderer.send('log-popout-theme', theme),
  pairPopoutTheme: (theme) => ipcRenderer.send('pair-popout-theme', theme),
  qsoPopoutClose: () => ipcRenderer.send('qso-popout-close'),
  sendQsoPopoutTheme: (theme) => ipcRenderer.send('qso-popout-theme', theme),
  onQsoPopoutStatus: (cb) => ipcRenderer.on('qso-popout-status', (_e, open) => cb(open)),
  // Pop-out spots window
  spotsPopoutOpen: () => ipcRenderer.send('spots-popout-open'),
  spotsPopoutClose: () => ipcRenderer.send('spots-popout-close'),
  sendSpotsPopoutTheme: (theme) => ipcRenderer.send('spots-popout-theme', theme),
  onSpotsPopoutStatus: (cb) => ipcRenderer.on('spots-popout-status', (_e, open) => cb(open)),
  // DX Cluster terminal pop-out
  clusterPopoutOpen: () => ipcRenderer.send('cluster-popout-open'),
  clusterPopoutClose: () => ipcRenderer.send('cluster-popout-close'),
  sendClusterPopoutTheme: (theme) => ipcRenderer.send('cluster-popout-theme', theme),
  onClusterPopoutStatus: (cb) => ipcRenderer.on('cluster-popout-status', (_e, open) => cb(open)),
  // Activation map pop-out
  actmapPopoutOpen: () => ipcRenderer.send('actmap-popout-open'),
  actmapPopoutData: (data) => ipcRenderer.send('actmap-popout-data', data),
  actmapPopoutContact: (data) => ipcRenderer.send('actmap-popout-contact', data),
  actmapPopoutTheme: (theme) => ipcRenderer.send('actmap-popout-theme', theme),
  onActmapPopoutStatus: (cb) => ipcRenderer.on('actmap-popout-status', (_e, open) => cb(open)),
  // VFO pop-out
  vfoPopoutOpen: () => ipcRenderer.send('vfo-popout-open'),
  vfoPopoutTheme: (theme) => ipcRenderer.send('vfo-popout-theme', theme),
  vfoTunedSpot: (spot) => ipcRenderer.send('vfo-tuned-spot', spot),
  onVfoPopoutStatus: (cb) => ipcRenderer.on('vfo-popout-status', (_e, open) => cb(open)),
  // JTCAT pop-out
  jtcatPopoutOpen: () => ipcRenderer.send('jtcat-popout-open'),
  jtcatPopoutTheme: (theme) => ipcRenderer.send('jtcat-popout-theme', theme),
  onJtcatPopoutStatus: (cb) => ipcRenderer.on('jtcat-popout-status', (_e, open) => cb(open)),
  onJtcatPopoutReply: (cb) => ipcRenderer.on('jtcat-popout-reply', (_e, data) => cb(data)),
  onJtcatPopoutCallCq: (cb) => ipcRenderer.on('jtcat-popout-call-cq', () => cb()),
  onJtcatPopoutCancelQso: (cb) => ipcRenderer.on('jtcat-popout-cancel-qso', () => cb()),
  sendJtcatQsoState: (state) => ipcRenderer.send('jtcat-qso-state-update', state),
  // SSTV pop-out
  sstvPopoutOpen: () => ipcRenderer.send('sstv-popout-open'),
  sstvPopoutTheme: (theme) => ipcRenderer.send('sstv-popout-theme', theme),
  // Bandspread pop-out
  bandspreadPopoutOpen: () => ipcRenderer.send('bandspread-popout-open'),
  bandspreadPopoutClose: () => ipcRenderer.send('bandspread-popout-close'),
  sendBandspreadPopoutTheme: (theme) => ipcRenderer.send('bandspread-popout-theme', theme),
  onBandspreadPopoutStatus: (cb) => ipcRenderer.on('bandspread-popout-status', (_e, open) => cb(open)),
  // Push the main window's filtered spot list + a band hint to the bandspread
  // popout so it mirrors what Table View is showing.
  bandspreadPopoutPush: (payload) => ipcRenderer.send('bandspread-popout-push', payload),
  onBandspreadTunedSpot: (cb) => ipcRenderer.on('bandspread-tuned-spot', (_e, payload) => cb(payload)),
  // CW Keyer
  cwPaddleDit: (pressed) => ipcRenderer.send('cw-paddle-dit', pressed),
  cwPaddleDah: (pressed) => ipcRenderer.send('cw-paddle-dah', pressed),
  cwSetWpm: (wpm) => ipcRenderer.send('cw-set-wpm', wpm),
  cwStop: () => ipcRenderer.send('cw-stop'),
  sendCwText: (text) => ipcRenderer.send('send-cw-text', text),
  voiceMacroPtt: (state) => ipcRenderer.send('voice-macro-ptt', state),
  exportSettings: () => ipcRenderer.invoke('export-settings'),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  relaunch: () => ipcRenderer.send('app-relaunch'),
  voiceMacroSave: (idx, base64) => ipcRenderer.invoke('voice-macro-save', idx, base64),
  voiceMacroLoad: (idx) => ipcRenderer.invoke('voice-macro-load', idx),
  voiceMacroDelete: (idx) => ipcRenderer.invoke('voice-macro-delete', idx),
  voiceMacroList: () => ipcRenderer.invoke('voice-macro-list'),
  voiceMacroLabelsSave: (labels) => ipcRenderer.invoke('voice-macro-labels-save', labels),
  onVoiceMacrosUpdated: (cb) => ipcRenderer.on('voice-macros-updated', () => cb()),
  // Phone-tapped macro slot — main relays here so the renderer's playback
  // chain (which owns the audio path) handles it the same as a local click.
  onPlayVoiceMacro: (cb) => ipcRenderer.on('play-voice-macro', (_e, idx) => cb(idx)),
  cwCancel: () => ipcRenderer.send('cw-cancel'),
  onCwEcho: (cb) => ipcRenderer.on('cw-echo', (_e, data) => cb(data)),
  onWinkeyerBusy: (cb) => ipcRenderer.on('winkeyer-busy', (_e, busy) => cb(busy)),
  // Activator mode — parks DB
  fetchParksDb: (prefix) => ipcRenderer.invoke('fetch-parks-db', prefix),
  searchParks: (query) => ipcRenderer.invoke('search-parks', query),
  getPark: (ref) => ipcRenderer.invoke('get-park', ref),
  parksDbStatus: () => ipcRenderer.invoke('parks-db-status'),
  exportActivationAdif: (data) => ipcRenderer.invoke('export-activation-adif', data),
  exportActivationAdifPerPark: (data) => ipcRenderer.invoke('export-activation-adif-perpark', data),
  uploadActivationToPota: (data) => ipcRenderer.invoke('upload-activation-to-pota', data),
  getPastActivations: () => ipcRenderer.invoke('get-past-activations'),
  deleteActivation: (parkRef, date) => ipcRenderer.invoke('delete-activation', parkRef, date),
  resolveCallsignLocations: (callsigns) => ipcRenderer.invoke('resolve-callsign-locations', callsigns),
  captureActmapPopout: () => ipcRenderer.invoke('capture-actmap-popout'),
  captureMainWindowRect: (rect) => ipcRenderer.invoke('capture-main-window-rect', rect),
  saveShareImage: (data) => ipcRenderer.invoke('save-share-image', data),
  // JTCAT (FT8/FT4)
  jtcatStart: (mode) => ipcRenderer.send('jtcat-start', mode),
  jtcatStop: () => ipcRenderer.send('jtcat-stop'),
  jtcatSetMode: (mode) => ipcRenderer.send('jtcat-set-mode', mode),
  jtcatSetTxFreq: (hz) => ipcRenderer.send('jtcat-set-tx-freq', hz),
  jtcatSetRxFreq: (hz) => ipcRenderer.send('jtcat-set-rx-freq', hz),
  jtcatSetAudioLatencyMs: (payload) => ipcRenderer.send('jtcat-set-audio-latency-ms', payload),
  onJtcatAudioLatency: (cb) => ipcRenderer.on('jtcat-audio-latency', (_e, data) => cb(data)),
  jtcatSetHoldTxFreq: (enabled) => ipcRenderer.send('jtcat-set-hold-tx-freq', !!enabled),
  jtcatEnableTx: (enabled) => ipcRenderer.send('jtcat-enable-tx', enabled),
  jtcatHaltTx: () => ipcRenderer.send('jtcat-halt-tx'),
  jtcatTuneToggle: () => ipcRenderer.send('jtcat-tune-toggle'),
  jtcatSetTxMsg: (text) => ipcRenderer.send('jtcat-set-tx-msg', text),
  jtcatSetTxSlot: (slot) => ipcRenderer.send('jtcat-set-tx-slot', slot),
  jtcatTxComplete: () => ipcRenderer.send('jtcat-tx-complete'),
  jtcatAudio: (buf) => ipcRenderer.send('jtcat-audio', buf),
  jtcatLog: (msg) => ipcRenderer.send('jtcat-log', msg),
  jtcatQuietFreq: (hz) => ipcRenderer.send('jtcat-quiet-freq', hz),
  jtcatSpectrum: (bins) => ipcRenderer.send('jtcat-spectrum', bins),
  onJtcatDecode: (cb) => ipcRenderer.on('jtcat-decode', (_e, data) => cb(data)),
  onJtcatCycle: (cb) => ipcRenderer.on('jtcat-cycle', (_e, data) => cb(data)),
  onJtcatSpectrum: (cb) => ipcRenderer.on('jtcat-spectrum', (_e, data) => cb(data)),
  onJtcatStatus: (cb) => ipcRenderer.on('jtcat-status', (_e, data) => cb(data)),
  onJtcatTxAudio: (cb) => ipcRenderer.on('jtcat-tx-audio', (_e, data) => cb(data)),
  onJtcatSetTxGain: (cb) => ipcRenderer.on('jtcat-set-tx-gain', (_e, level) => cb(level)),
  onJtcatSetRxGain: (cb) => ipcRenderer.on('jtcat-set-rx-gain', (_e, level) => cb(level)),
  onJtcatTxStatus: (cb) => ipcRenderer.on('jtcat-tx-status', (_e, data) => cb(data)),
  onJtcatTuneState: (cb) => ipcRenderer.on('jtcat-tune-state', (_e, data) => cb(data)),
  onJtcatTuneAudioStart: (cb) => ipcRenderer.on('jtcat-tune-audio-start', () => cb()),
  onJtcatTuneAudioStop: (cb) => ipcRenderer.on('jtcat-tune-audio-stop', () => cb()),
  onJtcatStartForRemote: (cb) => ipcRenderer.on('jtcat-start-for-remote', () => cb()),
  onJtcatStopForRemote: (cb) => ipcRenderer.on('jtcat-stop-for-remote', () => cb()),
  // FreeDV Digital Voice
  freedvStart: (mode) => ipcRenderer.send('freedv-start', mode),
  freedvStop: () => ipcRenderer.send('freedv-stop'),
  freedvSetMode: (mode) => ipcRenderer.send('freedv-set-mode', mode),
  freedvRxAudio: (buf) => ipcRenderer.send('freedv-rx-audio', buf),
  freedvTxAudio: (buf) => ipcRenderer.send('freedv-tx-audio', buf),
  freedvSetTx: (enabled) => ipcRenderer.send('freedv-set-tx', enabled),
  freedvSetSquelch: (enabled, threshold) => ipcRenderer.send('freedv-set-squelch', enabled, threshold),
  onFreedvRxSpeech: (cb) => ipcRenderer.on('freedv-rx-speech', (_e, data) => cb(data)),
  onFreedvTxModem: (cb) => ipcRenderer.on('freedv-tx-modem', (_e, data) => cb(data)),
  onFreedvSync: (cb) => ipcRenderer.on('freedv-sync', (_e, data) => cb(data)),
  onFreedvStatus: (cb) => ipcRenderer.on('freedv-status', (_e, data) => cb(data)),
  onOpenLogForm: (cb) => ipcRenderer.on('open-log-form', () => cb()),
  onFreedvAutoStart: (cb) => ipcRenderer.on('freedv-auto-start', (_e, mode) => cb(mode)),
  onFreedvAutoStop: (cb) => ipcRenderer.on('freedv-auto-stop', () => cb()),
  // Zoom
  setZoom: (factor) => webFrame.setZoomFactor(factor),
  getZoom: () => webFrame.getZoomFactor(),
  onCwKey: (cb) => ipcRenderer.on('cw-key', (_e, data) => cb(data)),
  onCwKeyerStatus: (cb) => ipcRenderer.on('cw-keyer-status', (_e, s) => cb(s)),
  onCwText: (cb) => ipcRenderer.on('cw-text', (_e, data) => cb(data)),
  // Remote Access
  getLocalIPs: () => ipcRenderer.invoke('get-local-ips'),
  // Club Station Mode
  chooseClubCsvFile: () => ipcRenderer.invoke('choose-club-csv-file'),
  previewClubCsv: (csvPath) => ipcRenderer.invoke('preview-club-csv', csvPath),
  hashClubPasswords: (csvPath) => ipcRenderer.invoke('hash-club-passwords', csvPath),
  createClubCsv: (rigNames) => ipcRenderer.invoke('create-club-csv', rigNames),
  // Remote Launcher
  installLauncher: () => ipcRenderer.invoke('install-launcher'),
  uninstallLauncher: () => ipcRenderer.invoke('uninstall-launcher'),
  // Rig Control Panel
  rigControl: (data) => ipcRenderer.invoke('rig-control', data),
  getRigCommands: () => ipcRenderer.invoke('get-rig-commands'),
  saveRigCommandOverride: (key, value) => ipcRenderer.invoke('save-rig-command-override', { key, value }),
  resetAllRigCommands: () => ipcRenderer.invoke('reset-all-rig-commands'),
  onRigState: (cb) => ipcRenderer.on('rig-state', (_e, state) => cb(state)),
  onRemoteTxState: (cb) => ipcRenderer.on('remote-tx-state', (_e, state) => cb(state)),
  onRemoteStatus: (cb) => ipcRenderer.on('remote-status', (_e, s) => cb(s)),
  onReloadPrefs: (cb) => ipcRenderer.on('reload-prefs', () => cb()),
  tgxlSelectAntenna: (port) => ipcRenderer.invoke('tgxl-select-antenna', port),
  tgxlGetStatus: () => ipcRenderer.invoke('tgxl-get-status'),
  onTgxlStatus: (cb) => ipcRenderer.on('tgxl-status', (_e, s) => cb(s)),
  onRestartJtcatAudio: (cb) => ipcRenderer.on('restart-jtcat-audio', () => cb()),
  // Cloud Sync
  qrzDownloadLogbook: () => ipcRenderer.invoke('qrz-download-logbook'),
  qrzDebugDump: () => ipcRenderer.invoke('qrz-debug-dump'),
  cloudGoogleSignIn: () => ipcRenderer.invoke('cloud-google-signin'),
  cloudLogin: (email, password) => ipcRenderer.invoke('cloud-login', email, password),
  cloudRegister: (email, password, callsign) => ipcRenderer.invoke('cloud-register', email, password, callsign),
  cloudLogout: () => ipcRenderer.invoke('cloud-logout'),
  cloudGetStatus: () => ipcRenderer.invoke('cloud-get-status'),
  cloudSyncNow: () => ipcRenderer.invoke('cloud-sync-now'),
  cloudBulkPrepare: () => ipcRenderer.invoke('cloud-bulk-prepare'),
  cloudBulkUpload: () => ipcRenderer.invoke('cloud-bulk-upload'),
  cloudDownloadAdif: () => ipcRenderer.invoke('cloud-download-adif'),
  cloudVerifySubscription: () => ipcRenderer.invoke('cloud-verify-subscription'),
  cloudSaveBmacEmail: (email) => ipcRenderer.invoke('cloud-save-bmac-email', email),
  cloudOpenSubscribe: () => ipcRenderer.invoke('cloud-open-subscribe'),
  cloudOpenManage: () => ipcRenderer.invoke('cloud-open-manage'),
  cloudGetSettings: () => ipcRenderer.invoke('cloud-get-settings'),
  cloudPutSettings: (data) => ipcRenderer.invoke('cloud-put-settings', data),
  onCloudSyncStatus: (cb) => ipcRenderer.on('cloud-sync-status', (_e, data) => cb(data)),
  // Main -> JTCAT popout: push currently-visible spot calls for decode-row
  // highlighting (Tyler K0OTC feature request, 2026-04-22).
  jtcatSpotsHighlight: (data) => ipcRenderer.send('jtcat-spots-highlight', data),
  // POTA.app Sync (parks-worked CSV auto-import)
  // Per-spot history lookup (POTA/WWFF via POTA.app, DXC/RBN via local buffers)
  potaSpotHistory: (data) => ipcRenderer.invoke('pota-spot-history', data),
  potaSyncStatus: () => ipcRenderer.invoke('pota-sync-status'),
  potaSyncConnect: () => ipcRenderer.invoke('pota-sync-connect'),
  potaSyncDisconnect: () => ipcRenderer.invoke('pota-sync-disconnect'),
  potaSyncNow: () => ipcRenderer.invoke('pota-sync-now'),
  potaSyncSetEnabled: (v) => ipcRenderer.invoke('pota-sync-set-enabled', v),
  potaSyncSetInterval: (v) => ipcRenderer.invoke('pota-sync-set-interval', v),
  onPotaSyncStatus: (cb) => ipcRenderer.on('pota-sync-status', (_e, data) => cb(data)),
  onCloudUploadProgress: (cb) => ipcRenderer.on('cloud-upload-progress', (_e, data) => cb(data)),
});
